# Generated by Django 2.0.13 on 2019-04-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190429_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.AddField(
            model_name='product',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
