# Generated by Django 2.0.13 on 2019-04-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190429_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='view_count',
            new_name='add_money',
        ),
        migrations.AddField(
            model_name='product',
            name='use_money',
            field=models.IntegerField(default=0),
        ),
    ]
